# This is a basic workflow to help you get started with Actions

name: Lint Cyder

on:
  push:
  pull_request:

jobs:
  build:
    name: Lint Cyder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Lint Cyder
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
