name: Lint

on:
  push:
jobs:
  error_prone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Google error-prone
        uses: github/super-linter@v4.9.4
