name: Cyder Statistics

on:
  push:
    branches:
      - main
  schedule: [{cron: "0 0 * * *"}]
jobs:
  generate_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r actions/requirements.txt

      - name: Run statistic generator
        run: |
          python ./actions/stat_generator.py

      - name: Commit generated files
        run: |
          git config --local user.email "nate@nathancheshire.com"
          git config --local user.name "NathanCheshire"
          git add .
          git commit -m "update README statistics"

      - name: Push changes
        run: |
          git push -u origin main
