name: Cyder Statistics

on:
  push:
    branches:
    - main
  schedule: [{cron: "0 0 * * *"}]
jobs:
  generate_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dependencies
        run: pip install -r actions/requirements.txt

      - name: run script
        run: |
          python ./actions/stat_generator.py
      
      - name: commit generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "update statistics"
          
      - name: push changes
        run: |
          git push -u origin main
